version: '3.8'

services:
  mongo:
    image: mongo:4.4
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./back
    ports:
      - '4000:4000'
    depends_on:
      - mongo
    volumes:
      - ./back/.env:/app/.env

  frontend:
    build: ./front
    ports:
      - '3000:3000'
    depends_on:
      - backend

volumes:
  mongo-data:
